"""add error_message to audit_logs

Revision ID: a58c2f0bdc97
Revises: 647dcf61de18
Create Date: 2026-08-22 13:10:45.468400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58c2f0bdc97'
down_revision: Union[str, None] = '647dcf61de18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'error_message')
    # ### end Alembic commands ###
